p8105_hw2_xl3712
================
Xieyu Liu
2026-10-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1

``` r
Transit_df = read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")|>
  janitor::clean_names()|>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(entry = case_match(
    entry,
    "YES" ~ T,
    "NO" ~ F
  ))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ T, "NO" ~ F)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

The dataset contains line, station name, station latitude, station
longitude, routes 1 to 11, entry, vending, entrance type and ADA
compliant. I first imported the NYC Transit Data, and cleaned the
variable names. Then, I select the relevant columns and converted the
entry variable from “YES” or “NO” to TRUE or FALSE. The dataset has 1868
rows and 19 columns. These data are not tidy because the routes served
are stored across 11 columns instead of one variable.

``` r
Transit_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

``` r
Transit_df |>
  distinct(line, station_name, ada) |>
  filter(ada == "TRUE") |>
  nrow()
```

    ## [1] 84

There are 84 ADA-compliant stations.

``` r
Transit_df |>
  filter(vending == "NO")|>
  summarize(
    proportion = mean(entry)
  )
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

Among station entrance/exits without vending, 37.7% allow entrance.

``` r
Transit_df_reformat = Transit_df |>
  mutate(across(route1:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

``` r
Transit_df_reformat|>
  filter(route_name == "A")|>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

There are 60 distinct stations that serve the A train.

``` r
Transit_df_reformat|>
  filter(route_name == "A")|>
  distinct(line, station_name, ada) |>
  filter(ada == "TRUE") |>
  nrow()
```

    ## [1] 17

Of these stations, 17 are ADA compliant.

## Problem 2

``` r
library(readxl)
```

``` r
Mr_Trash_Wheel_df = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Mr. Trash Wheel",
             skip = 1,
             range = cell_cols(1:14)
             )|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))|>
  mutate(
    sports_balls = as.integer(round(sports_balls))
    )
```

``` r
Professor_Trash_Wheel_df = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Professor Trash Wheel",
             skip = 1
             ) |>
  janitor::clean_names()|>
  filter(!is.na(dumpster))
```

``` r
Gwynnda_df = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx",
             sheet = "Gwynns Falls Trash Wheel",
             skip = 1
             )|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))
```

``` r
Mr_Trash_Wheel_df = 
  Mr_Trash_Wheel_df|>
  mutate(trash_wheel = "Mr",
         year = as.character(year))

Professor_Trash_Wheel_df =
  Professor_Trash_Wheel_df|>
  mutate(trash_wheel = "Professor",
         year = as.character(year))

Gwynnda_df = 
  Gwynnda_df|>
  mutate(trash_wheel = "Gwynnda",
         year = as.character(year))

Trash_Wheel_df = 
  bind_rows(
    Mr_Trash_Wheel_df,
    Professor_Trash_Wheel_df,
    Gwynnda_df
            )|>
  relocate(trash_wheel)
```

The resulting dataset contains 1188 observations and includes
information on trash wheel type, dumpster number, collection date, and
the amount and type of trash collected. Key variables include
`trash_wheel`, `dumpster`, `date`, `weight_tons`, `volume_cubic_yards`,
and variables measuring different types, such as `plastic_bottles` and
`polystyrene`.

``` r
Trash_Wheel_df|>
  filter(trash_wheel == "Professor")|>
  summarise(total_weight = sum(weight_tons))
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         282.

The total weight of trash collected by Professor Trash Wheel was 282
tons.

``` r
Trash_Wheel_df|>
  filter(trash_wheel == "Gwynnda",
         month == "June",
         year == "2022")|>
  summarise(total_number_of_cigarette_butts = sum(cigarette_butts))
```

    ## # A tibble: 1 × 1
    ##   total_number_of_cigarette_butts
    ##                             <dbl>
    ## 1                           18120

The total number of cigarette butts collected by Gwynnda in June 2022
was 18120.

## Problem 3

``` r
baseline_df = 
  read_csv("data/MCI_baseline.csv",
           na = ".",
           skip = 1)|>
  janitor::clean_names()|>
  mutate(sex = 
           factor(sex,
                  levels = c(0,1),
                  labels = c("Female","Male")),
         apoe4 = factor(apoe4,
                        levels = c(0,1),
                        labels = c("Non-carrier","Carrier")))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The baseline demographics dataset contains 483 participants and 6
variables. During import, missing values represented by “.” were
converted to NA, and the first row was skipped because it contained
descriptions of the variables rather than variable names. Variable names
were cleaned using `clean_names()`. Sex was recoded as a factor with
levels of Female and Male, and APOE4 carrier status was recoded as a
factor with levels of Non-carrier and Carrier. The study participants
were free of MCI at baseline. The `age_at_onset` variable contains
missing values for participants who remained MCI-free during the
follow-up period.

``` r
baseline_df|>
  summarise(
    n_recruited = n(),
    n_mci = sum(!is.na(age_at_onset)))
```

    ## # A tibble: 1 × 2
    ##   n_recruited n_mci
    ##         <int> <int>
    ## 1         483    97

483 participants were recruited, and 97 of them developed MCI.

``` r
baseline_df|>
  summarise(average_age = mean(current_age))
```

    ## # A tibble: 1 × 1
    ##   average_age
    ##         <dbl>
    ## 1        65.0

The average baseline age is 65.

``` r
baseline_df|>
  filter(sex == "Female")|>
  summarise(
    proportion = mean(apoe4 == "Carrier") *100
  )
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1       29.9

29.9% of the women in the study are APOE4 carriers.

``` r
amyloid_df = 
  read_csv("data/mci_amyloid.csv",
           skip = 1,
           na = c("NA","Na"))|>
  janitor::clean_names()|>
  pivot_longer(baseline:time_8,
               names_to = "time",
               names_prefix = "time_",
               values_to = "amyloid_42_40")|>
  mutate(time = if_else(time == "baseline","0",time),
         time = as.numeric(time)
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
dim(amyloid_df)
```

    ## [1] 2435    3

The longitudinal biomarker dataset contains repeated measurements of the
amyloid 42/40 ratio for study participants at baseline and at 2, 4, 6,
and 8 years after baseline. During import, the first row was skipped,
and “NA” and “Na” were specified as missing values. Variable names were
cleaned using `clean_names()`. The dataset was reshaped from wide to
long format using `pivot_longer()`, with measurement time stored in a
single `time` variable and the corresponding amyloid 42/40 ratio stored
in `amyloid_42_40`. Baseline was coded as 0 years, and the time variable
was converted to numeric. The resulting dataset contains 2435
observations and 3 variables.

``` r
baseline_df|>
  anti_join(amyloid_df, by = c("id" = "study_id"))|>
  nrow()
```

    ## [1] 8

``` r
amyloid_df|>
  anti_join(baseline_df, by = c("study_id" = "id"))|>
  distinct(study_id)|>
  nrow()
```

    ## [1] 12

8 participants appear only in the baseline dataset, while 12
participants appear only in the amyloid dataset.

``` r
combined_df = 
  baseline_df|>
  inner_join(amyloid_df,
             by = c("id" = "study_id"))

combined_df|>
  distinct(id)|>
  nrow()
```

    ## [1] 475

``` r
write_csv(combined_df,"data/MCI_combined.csv")
```

The resulting dataset contains 475 participants and 2375 observations
across 8 variables. It includes demographic characteristics such as age,
sex, education, and APOE4 carrier status, as well as longitudinal
amyloid 42/40 ratio measurements at different follow-up times.
